config/routes.rb
# == Route Map
#
#                  Prefix Verb   URI Pattern                                         Controller#Action
#                    root GET    /                                                   session#new
#                   users GET    /users(.:format)                                    users#index
#                         POST   /users(.:format)                                    users#create
#                new_user GET    /users/new(.:format)                                users#new
#               edit_user GET    /users/:id/edit(.:format)                           users#edit
#                    user GET    /users/:id(.:format)                                users#show
#                         PATCH  /users/:id(.:format)                                users#update
#                         PUT    /users/:id(.:format)                                users#update
#                         DELETE /users/:id(.:format)                                users#destroy
#               airplanes GET    /airplanes(.:format)                                airplanes#index
#                         POST   /airplanes(.:format)                                airplanes#create
#            new_airplane GET    /airplanes/new(.:format)                            airplanes#new
#           edit_airplane GET    /airplanes/:id/edit(.:format)                       airplanes#edit
#                airplane GET    /airplanes/:id(.:format)                            airplanes#show
#                         PATCH  /airplanes/:id(.:format)                            airplanes#update
#                         PUT    /airplanes/:id(.:format)                            airplanes#update
#                         DELETE /airplanes/:id(.:format)                            airplanes#destroy
#     flight_reservations GET    /flights/:flight_id/reservations(.:format)          reservations#index
#                         POST   /flights/:flight_id/reservations(.:format)          reservations#create
#  new_flight_reservation GET    /flights/:flight_id/reservations/new(.:format)      reservations#new
# edit_flight_reservation GET    /flights/:flight_id/reservations/:id/edit(.:format) reservations#edit
#      flight_reservation GET    /flights/:flight_id/reservations/:id(.:format)      reservations#show
#                         PATCH  /flights/:flight_id/reservations/:id(.:format)      reservations#update
#                         PUT    /flights/:flight_id/reservations/:id(.:format)      reservations#update
#                         DELETE /flights/:flight_id/reservations/:id(.:format)      reservations#destroy
#                 flights GET    /flights(.:format)                                  flights#index
#                         POST   /flights(.:format)                                  flights#create
#              new_flight GET    /flights/new(.:format)                              flights#new
#             edit_flight GET    /flights/:id/edit(.:format)                         flights#edit
#                  flight GET    /flights/:id(.:format)                              flights#show
#                         PATCH  /flights/:id(.:format)                              flights#update
#                         PUT    /flights/:id(.:format)                              flights#update
#                         DELETE /flights/:id(.:format)                              flights#destroy
#                   login GET    /login(.:format)                                    session#new
#                         POST   /login(.:format)                                    session#create
#                         DELETE /login(.:format)                                    session#destroy
#

Rails.application.routes.draw do
  get 'liger/index'

  root :to => 'session#new'

  resources :users
  resources :airplanes do
    resources :flights do
      resources :reservations
    end
  end
  


  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/flight.rb
# == Schema Information
#
# Table name: flights
#
#  id          :integer          not null, primary key
#  flight_no   :integer
#  departure   :string
#  destination :string
#  date        :string
#  plane_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Flight < ActiveRecord::Base
  belongs_to :airplane
  has_many :reservations
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
    respond_to do |format|
      format.html { }  # Default behaviour: show the associated view
      format.json { render :json => @flights } # Show the associated view in Json
    end
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:flight_no, :departure, :destination, :date, :plane_id)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :flight_no %><br>
    <%= f.number_field :flight_no %>
  </div>
  <div class="field">
    <%= f.label :departure %><br>
    <%= f.text_field :departure %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :plane_id %><br>
    <%= f.number_field :plane_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Flights</h1>

<table>
  <thead>
    <tr>
      <th>Flight no</th>
      <th>Departure</th>
      <th>Destination</th>
      <th>Date</th>
      <th>Plane</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.flight_no %></td>
        <td><%= flight.departure %></td>
        <td><%= flight.destination %></td>
        <td><%= flight.date %></td>
        <td><%= flight.plane_id %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flight no:</strong>
  <%= @flight.flight_no %>
</p>

<p>
  <strong>Departure:</strong>
  <%= @flight.departure %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flight.destination %>
</p>

<p>
  <strong>Date:</strong>
  <%= @flight.date %>
</p>

<p>
  <strong>Plane:</strong>
  <%= @flight.plane_id %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>