config/routes.rb
# == Route Map
#
#                  Prefix Verb   URI Pattern                                         Controller#Action
#                    root GET    /                                                   session#new
#                   users GET    /users(.:format)                                    users#index
#                         POST   /users(.:format)                                    users#create
#                new_user GET    /users/new(.:format)                                users#new
#               edit_user GET    /users/:id/edit(.:format)                           users#edit
#                    user GET    /users/:id(.:format)                                users#show
#                         PATCH  /users/:id(.:format)                                users#update
#                         PUT    /users/:id(.:format)                                users#update
#                         DELETE /users/:id(.:format)                                users#destroy
#               airplanes GET    /airplanes(.:format)                                airplanes#index
#                         POST   /airplanes(.:format)                                airplanes#create
#            new_airplane GET    /airplanes/new(.:format)                            airplanes#new
#           edit_airplane GET    /airplanes/:id/edit(.:format)                       airplanes#edit
#                airplane GET    /airplanes/:id(.:format)                            airplanes#show
#                         PATCH  /airplanes/:id(.:format)                            airplanes#update
#                         PUT    /airplanes/:id(.:format)                            airplanes#update
#                         DELETE /airplanes/:id(.:format)                            airplanes#destroy
#     flight_reservations GET    /flights/:flight_id/reservations(.:format)          reservations#index
#                         POST   /flights/:flight_id/reservations(.:format)          reservations#create
#  new_flight_reservation GET    /flights/:flight_id/reservations/new(.:format)      reservations#new
# edit_flight_reservation GET    /flights/:flight_id/reservations/:id/edit(.:format) reservations#edit
#      flight_reservation GET    /flights/:flight_id/reservations/:id(.:format)      reservations#show
#                         PATCH  /flights/:flight_id/reservations/:id(.:format)      reservations#update
#                         PUT    /flights/:flight_id/reservations/:id(.:format)      reservations#update
#                         DELETE /flights/:flight_id/reservations/:id(.:format)      reservations#destroy
#                 flights GET    /flights(.:format)                                  flights#index
#                         POST   /flights(.:format)                                  flights#create
#              new_flight GET    /flights/new(.:format)                              flights#new
#             edit_flight GET    /flights/:id/edit(.:format)                         flights#edit
#                  flight GET    /flights/:id(.:format)                              flights#show
#                         PATCH  /flights/:id(.:format)                              flights#update
#                         PUT    /flights/:id(.:format)                              flights#update
#                         DELETE /flights/:id(.:format)                              flights#destroy
#                   login GET    /login(.:format)                                    session#new
#                         POST   /login(.:format)                                    session#create
#                         DELETE /login(.:format)                                    session#destroy
#

Rails.application.routes.draw do
  get 'liger/index'

  root :to => 'session#new'

  resources :users
  resources :airplanes do
    resources :flights do
      resources :reservations
    end
  end
  


  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/airplane.rb
# == Schema Information
#
# Table name: airplanes
#
#  id         :integer          not null, primary key
#  name       :string
#  row        :integer
#  column     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Airplane < ActiveRecord::Base
  has_many :flights
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  before_action :set_airplane, only: [:show, :edit, :update, :destroy]

  # GET /airplanes
  # GET /airplanes.json
  def index
    @airplanes = Airplane.all
    respond_to do |format|
      format.html { }  # Default behaviour: show the associated view
      format.json { render :json => @airplanes } # Show the associated view in Json
    end
  end

  # GET /airplanes/1
  # GET /airplanes/1.json
  def show
  end

  # GET /airplanes/new
  def new
    @airplane = Airplane.new
  end

  # GET /airplanes/1/edit
  def edit
  end

  # POST /airplanes
  # POST /airplanes.json
  def create
    @airplane = Airplane.new(airplane_params)

    respond_to do |format|
      if @airplane.save
        format.html { redirect_to @airplane, notice: 'Airplane was successfully created.' }
        format.json { render :show, status: :created, location: @airplane }
      else
        format.html { render :new }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airplanes/1
  # PATCH/PUT /airplanes/1.json
  def update
    respond_to do |format|
      if @airplane.update(airplane_params)
        format.html { redirect_to @airplane, notice: 'Airplane was successfully updated.' }
        format.json { render :show, status: :ok, location: @airplane }
      else
        format.html { render :edit }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airplanes/1
  # DELETE /airplanes/1.json
  def destroy
    @airplane.destroy
    respond_to do |format|
      format.html { redirect_to airplanes_url, notice: 'Airplane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airplane
      @airplane = Airplane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airplane_params
      params.require(:airplane).permit(:name, :row, :column)
    end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/views/airplanes/_form.html.erb
<%= form_for(@airplane) do |f| %>
  <% if @airplane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@airplane.errors.count, "error") %> prohibited this airplane from being saved:</h2>

      <ul>
      <% @airplane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :row %><br>
    <%= f.number_field :row %>
  </div>
  <div class="field">
    <%= f.label :column %><br>
    <%= f.number_field :column %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/airplanes/edit.html.erb
<h1>Editing Airplane</h1>

<%= render 'form' %>

<%= link_to 'Show', @airplane %> |
<%= link_to 'Back', airplanes_path %>

app/views/airplanes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Airplanes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Row</th>
      <th>Column</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @airplanes.each do |airplane| %>
      <tr>
        <td><%= airplane.name %></td>
        <td><%= airplane.row %></td>
        <td><%= airplane.column %></td>
        <td><%= link_to 'Show', airplane %></td>
        <td><%= link_to 'Edit', edit_airplane_path(airplane) %></td>
        <td><%= link_to 'Destroy', airplane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Airplane', new_airplane_path %>

app/views/airplanes/new.html.erb
<h1>New Airplane</h1>

<%= render 'form' %>

<%= link_to 'Back', airplanes_path %>

app/views/airplanes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @airplane.name %>
</p>

<p>
  <strong>Row:</strong>
  <%= @airplane.row %>
</p>

<p>
  <strong>Column:</strong>
  <%= @airplane.column %>
</p>

<%= link_to 'Edit', edit_airplane_path(@airplane) %> |
<%= link_to 'Back', airplanes_path %>