config/routes.rb
# == Route Map
#
#                  Prefix Verb   URI Pattern                                         Controller#Action
#                    root GET    /                                                   session#new
#                   users GET    /users(.:format)                                    users#index
#                         POST   /users(.:format)                                    users#create
#                new_user GET    /users/new(.:format)                                users#new
#               edit_user GET    /users/:id/edit(.:format)                           users#edit
#                    user GET    /users/:id(.:format)                                users#show
#                         PATCH  /users/:id(.:format)                                users#update
#                         PUT    /users/:id(.:format)                                users#update
#                         DELETE /users/:id(.:format)                                users#destroy
#               airplanes GET    /airplanes(.:format)                                airplanes#index
#                         POST   /airplanes(.:format)                                airplanes#create
#            new_airplane GET    /airplanes/new(.:format)                            airplanes#new
#           edit_airplane GET    /airplanes/:id/edit(.:format)                       airplanes#edit
#                airplane GET    /airplanes/:id(.:format)                            airplanes#show
#                         PATCH  /airplanes/:id(.:format)                            airplanes#update
#                         PUT    /airplanes/:id(.:format)                            airplanes#update
#                         DELETE /airplanes/:id(.:format)                            airplanes#destroy
#     flight_reservations GET    /flights/:flight_id/reservations(.:format)          reservations#index
#                         POST   /flights/:flight_id/reservations(.:format)          reservations#create
#  new_flight_reservation GET    /flights/:flight_id/reservations/new(.:format)      reservations#new
# edit_flight_reservation GET    /flights/:flight_id/reservations/:id/edit(.:format) reservations#edit
#      flight_reservation GET    /flights/:flight_id/reservations/:id(.:format)      reservations#show
#                         PATCH  /flights/:flight_id/reservations/:id(.:format)      reservations#update
#                         PUT    /flights/:flight_id/reservations/:id(.:format)      reservations#update
#                         DELETE /flights/:flight_id/reservations/:id(.:format)      reservations#destroy
#                 flights GET    /flights(.:format)                                  flights#index
#                         POST   /flights(.:format)                                  flights#create
#              new_flight GET    /flights/new(.:format)                              flights#new
#             edit_flight GET    /flights/:id/edit(.:format)                         flights#edit
#                  flight GET    /flights/:id(.:format)                              flights#show
#                         PATCH  /flights/:id(.:format)                              flights#update
#                         PUT    /flights/:id(.:format)                              flights#update
#                         DELETE /flights/:id(.:format)                              flights#destroy
#                   login GET    /login(.:format)                                    session#new
#                         POST   /login(.:format)                                    session#create
#                         DELETE /login(.:format)                                    session#destroy
#

Rails.application.routes.draw do
  get 'liger/index'

  root :to => 'session#new'

  resources :users
  resources :airplanes do
    resources :flights do
      resources :reservations
    end
  end
  


  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/reservation.rb
# == Schema Information
#
# Table name: reservations
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  row        :integer
#  column     :integer
#  flight_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :flight
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
    respond_to do |format|
      format.html { }  # Default behaviour: show the associated view
      format.json { render :json => @reservations } # Show the associated view in Json
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:user_id, :row, :column, :flight_id)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :row %><br>
    <%= f.number_field :row %>
  </div>
  <div class="field">
    <%= f.label :column %><br>
    <%= f.number_field :column %>
  </div>
  <div class="field">
    <%= f.label :flight_id %><br>
    <%= f.number_field :flight_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reservations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Row</th>
      <th>Column</th>
      <th>Flight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.user_id %></td>
        <td><%= reservation.row %></td>
        <td><%= reservation.column %></td>
        <td><%= reservation.flight_id %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @reservation.user_id %>
</p>

<p>
  <strong>Row:</strong>
  <%= @reservation.row %>
</p>

<p>
  <strong>Column:</strong>
  <%= @reservation.column %>
</p>

<p>
  <strong>Flight:</strong>
  <%= @reservation.flight_id %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>